<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Compile Remove="OrderData\**" />
		<Compile Remove="OrderDataService\**" />
		<Compile Remove="OrderManagerService\**" />
		<EmbeddedResource Remove="OrderData\**" />
		<EmbeddedResource Remove="OrderDataService\**" />
		<EmbeddedResource Remove="OrderManagerService\**" />
		<None Remove="OrderData\**" />
		<None Remove="OrderDataService\**" />
		<None Remove="OrderManagerService\**" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="OrderManagerService\OrderManagerService.csproj" />
  </ItemGroup>

</Project>
